(global-set-key (kbd "C-;") 'ibuffer)
(global-set-key (kbd "C-x C-b") 'ibuffer)
(global-set-key (kbd "C-z") 'undo)
(global-set-key (kbd "C-x C-r") 'ido-recentf-open)
(global-set-key (kbd "C-k") 'kill-and-join-forward)
(global-set-key (kbd "C-a") 'mark-whole-buffer)
(global-set-key (kbd "<f5>") 'previous-buffer)
(global-set-key (kbd "<f6>") 'next-buffer)
(global-set-key (kbd "C-f") 'isearch-forward)
(global-set-key (kbd "C-S-f") 'isearch-backward)
(global-set-key [home] 'beginning-of-line)
(global-set-key [end] 'end-of-line)
(global-set-key (kbd "M-<f4>") 'save-buffers-kill-terminal)
(global-set-key [(meta g)] 'goto-line)
(global-set-key (kbd "C-q")        'kill-buffer)

(global-set-key (kbd "C-s") 'save-buffer)
(global-set-key (kbd "C-x C-s") 'save-some-buffers)

(global-set-key (kbd "M-<left>")  'windmove-left)
(global-set-key (kbd "M-<right>") 'windmove-right)
(global-set-key (kbd "M-<up>")    'windmove-up)
(global-set-key (kbd "M-<down>")  'windmove-down)

(global-set-key (kbd "C-c c") 'ac-start)

;;(define-key global-map (kbd "RET") 'newline)

;;(global-set-key (kbd "C-d") 'kill-whole-line)
;;(global-set-key (kbd "<f10>") 'bookmark-bmenu-list)
;;(global-set-key (kbd "C-y") 'undo-tree-redo)
;;(global-set-key [(shift insert)] 'clipboard-yank)
;;(global-set-key [(control insert)] 'clipboard-kill-ring-save)
